//  hamiltonians.h
//  
//
//  Created by Patrick on 10/31/17.
//
//DO NOT edit this file manually unless absolutely necessary


#ifndef hamiltonians_h
#define hamiltonians_h

#include "basicSquare.h"
#include "EulerChar.h"
#endif /* hamiltonians_h */
