//
//
//DO NOT edit this file manually unless absolutely necessary
double SOURCE = 0.0;


#ifndef hamiltonians_h
#define hamiltonians_h

#include "basicSquare.h"

#include "EulerChar.h"
#include "curveDiff.h"
#endif /* hamiltonians_h */
